### ISSUE TITLE
Create Frontend Baseline Model

### ISSUE THREAD

**Issue by wilsonngja** [CS3219-AY2324S1/ay2324s1-course-assessment-g09#2]
The baseline model requires a basic UI that contains button and a backbone for list to be shown.
This baseline model will be used to kickstart on Assignment 1, which require CRUD operations to be displayed on a Landing Page.

**Comment by choonyongchan** [comment]
Important to setup a simple CI to test if the app compiles successfully, at the very least. Making a new issue
